### ISSUE TITLE
I have a problem with converting the graphics.

### ISSUE THREAD

**Issue by cloud263** [oscarpeters/ColorE-ink-converter#1]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /home/cfy/.local/lib/python3.8/site-packages (9.1.1)
Requirement already satisfied: tqdm in /home/cfy/.local/lib/python3.8/site-packages (4.64.0)
First stage converter:   0%|                        | 0/32 [00:00<?, ? Images/s]Photo_converter.py:131: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  img.thumbnail(size, Image.ANTIALIAS)
First stage converter:   3%|▌               | 1/32 [00:00<00:04,  7.59 Images/s]Traceback (most recent call last):
  File "Photo_converter.py", line 212, in <module>
    Pillow()
  File "Photo_converter.py", line 147, in Pillow
    raise NameError(
NameError: No pictures which end with either .png, .jpg or .jpeg
Error due to: default (29).jpg
First stage converter:   3%|▌               | 1/32 [00:00<00:06,  4.70 Images/s]

**Comment by oscarpeters** [comment]
Thanks, I try fix this in the upcomming week

**Comment by oscarpeters** [comment]
Is it just this picture that won't work? Or all sorts of jpeg, jpg or  png?

**Comment by cloud263** [comment]
Maybe there is a problem with the graphics format, I tried some more files and was able to convert successfully.
Best regards.

**Comment by oscarpeters** [comment]
Could you try and rename the "default (29).jpg" to something else .jpg and retry it?

**Comment by oscarpeters** [comment]
I have made some small changes, on windows i couldn't recreate the issue. Tried it on MacOs and found some issues which correspond to that of yours. I have a temporary fix for now.

**Comment by cloud263** [comment]
I tried the file that failed to convert before with the new version, and it converts perfectly. 
Thank you very much.
